import { Providers } from "@/lib/providers";
import "./globals.css";
import Fonts from "@/styles/fonts.js";
import PrivacyPolicy from "@/components/privacy-policy";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        {/* <Fonts /> */}

        <Providers>
          {children}
          <PrivacyPolicy />
        </Providers>
      </body>
    </html>
  );
}
