import { Providers } from "@/lib/providers";
import "./globals.css";
import Fonts from "@/lib/fonts";
import Loader from "@/components/loader/loading-page.js";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Fonts />
        <Loader>
          <Providers>{children}</Providers>
        </Loader>
      </body>
    </html>
  );
}
